pull_request_rules:
  - name: instruct bors to merge dependabot PRs with passing tests
    conditions:
      - "status-success=static_analysis"
      - "status-success=build (macos)"
      - "status-success=build (windows)"
      - "status-success=build (ubuntu)"
      - "status-success=e2e_test"
      - "status-success=npm_build"
      - "status-success=license/cla"
      - "author:dependabot[bot]"
    actions:
      comment:
        message: "bors r+"
  - name: instruct bors to merge PRs with passing tests and 2 approvals
    conditions:
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - "status-success=static_analysis"
      - "status-success=build (macos)"
      - "status-success=build (windows)"
      - "status-success=build (ubuntu)"
      - "status-success=e2e_test"
      - "status-success=npm_build"
      - "status-success=license/cla"
      - -conflict
      - label!=work-in-progress
      - label!=blocked
      - label!=no-mergify
      - head~=^(?!release.*).*$
    actions:
      comment:
        message: "bors r+"
  - name: Delete branch if the pull request is merged
    conditions:
      - merged
    actions:
      delete_head_branch:
  - name: nag if changelog is not updated
    conditions:
      - "author!=dependabot[bot]"
      - "files!=create/CHANGELOG.md"
      - "files!=scripts/CHANGELOG.md"
      - review-requested!=''
    actions:
      comment:
        message: "Are you sure the changelog does not need updating?"
