pull_request_rules:
  - name: instruct bors to merge dependabot PRs with passing tests
    conditions:
      - "status-success=CI / static_analysis (push)"
      - "status-success=CI / build (macos) (push)"
      - "status-success=CI / build (windows) (push)"
      - "status-success=CI / build (ubuntu) (push)"
      - "status-success=CI / e2e_test (ubuntu) (push)"
      - "author:dependabot-preview[bot]"
    actions:
      comment:
        message: "bors r+"
  - name: instruct bors to merge PRs with passing tests and 2 approvals
    conditions:
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - "status-success=CI / static_analysis (push)"
      - "status-success=CI / build (macos) (push)"
      - "status-success=CI / build (windows) (push)"
      - "status-success=CI / build (ubuntu) (push)"
      - "status-success=CI / e2e_test (ubuntu) (push)"
      - "status-success=license/cla"
      - -conflict
      - label!=work-in-progress
      - label!=blocked
      - label!=no-mergify
      - head~=^(?!release.*).*$
    actions:
      comment:
        message: "bors r+"
  - name: Delete branch if the pull request is merged
    conditions:
      - merged
    actions:
      delete_head_branch:
  - name: nag if changelog is not updated
    conditions:
      - "author!=dependabot-preview[bot]"
      - "files!=CHANGELOG.md"
      - review-requested!=''
    actions:
      comment:
        message: "Are you sure the changelog does not need updating?"
