pull_request_rules:
  - name: merge on CI success and 2 approvals
    conditions:
      - "status-success=ci/circleci: build_test"
      - "status-success=ci/circleci: static_analysis"
      - "status-success=license/cla"
      - "#approved-reviews-by>=2"
      - label!=work-in-progress
      - label!=blocked
      - label!=no-mergify
      - head~=^(?!release.*).*$
      - "#changes-requested-reviews-by=0"
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: merge
      delete_head_branch:
  - name: merge green dependabot PRs
    conditions:
      - "status-success=ci/circleci: build_test"
      - "status-success=ci/circleci: static_analysis"
      - "author:dependabot-preview[bot]"
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: merge
      delete_head_branch:
  - name: nag if changelog is not updated
    conditions:
      - "files~=(?!.*CHANGELOG.md.*)"
      - review-requested!=''
    actions:
      comment:
        message: "Are you sure the changelog does not need updating?"
