status = [
    "CI / static_analysis (push)",
    "CI / build (macos) (push)",
    "CI / build (ubuntu) (push)",
    "CI / build (windows) (push)",
    "CI / e2e_test (ubuntu) (push)",
]
pr_status = ["license/cla"]
