[package]
name = "create-comit-app"
version = "0.1.0"
authors = ["CoBloX developers <team@coblox.tech>"]
edition = "2018"

[dependencies]
bitcoincore-rpc = "0.8.0-rc1"
rust_bitcoin = { version = "0.19.1", package = "bitcoin" }
structopt = "0.3"
testcontainers = "0.7"
web3 = "0.8"

[dev-dependencies]
quickcheck = "0.7"
reqwest = "0.9"
