[package]
name = "create-comit-app"
version = "0.1.0"
authors = ["CoBloX developers <team@coblox.tech>"]
edition = "2018"

[dependencies]
bitcoincore-rpc = "0.8.0-rc1"
futures = "0.1"
port_check = "0.1"
rust_bitcoin = { version = "0.19.1", package = "bitcoin" }
shiplift = "0.5"
structopt = "0.3"
tempfile = "3.1.0"
testcontainers = "0.7"
tokio = "0.1"
tokio-process = "0.2"
toml = "0.5"
web3 = "0.8"

[dev-dependencies]
quickcheck = "0.7"
reqwest = "0.9"
