version: 2.1
workflows:
  version: 2
  main:
    jobs:
      - static_analysis
      - build_test

jobs:
  static_analysis:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      - RUST_TEST_THREADS: "8"
    steps:
      - run: sudo apt-get update
      - checkout
      - restore_caches
      - install_rust
      - run:
          name: "Run Format checks"
          command: |
            make check_format
      - run:
          name: "Run Clippy"
          command: make clippy
  build_test:
    working_directory: ~/workspace
    machine:
      image: ubuntu-1604:201903-01
    environment:
      - RUST_TEST_THREADS: "8"
    steps:
      - run: sudo apt-get update
      - checkout
      - restore_caches
      - install_rust
      - run:
          name: "Build"
          command: |
            make build
      - run:
          name: "Test"
          command: |
            make test
      - save_caches

commands:
  install_rust:
    steps:
      - run:
          name: "Install Rust"
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $(< rust-toolchain)
            source $HOME/.cargo/env
            echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
            rustc --version --verbose
            cargo --version --verbose
  restore_caches:
    steps:
      - restore_cache:
          keys:
            - rustup-{{ checksum "rust-toolchain" }}
            # We don't want multiple toolchains to pile up in our cache, so only restore the ones we actually use.
      - restore_cache:
          keys:
            - cargo-{{ .Branch }}
            - cargo
      - restore_cache:
          keys:
            - target-folder-{{ checksum "Cargo.lock" }}
            # We don't want the target folder to blow up over time, hence we only download the cache if it exactly matches `Cargo.lock`
  save_caches:
    steps:
      - save_cache:
          paths:
            - ~/.rustup
          key: rustup-{{ checksum "rust-toolchain" }}
      - save_cache:
          paths:
            - ~/.cargo
          key: cargo-{{ .Branch }}
      - save_cache:
          key: target-folder-{{ checksum "Cargo.lock" }}
          paths:
            - "./target"
