version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
    ignored_updates:
      # version of secp256k1 depends on bitcoin version, we should remove this once https://github.com/rust-bitcoin/rust-bitcoin/pull/344 gets merged and released
      - match:
          dependency_name: "secp256k1"
      # version of ethabi depends on web3 version and have to be updated in lockstep
      - match:
          dependency_name: "ethabi"
      # version of bytes depends on tokio version and have to be updated in lockstep
      - match:
          dependency_name: "bytes"
  - package_manager: "javascript"
    directory: "/new_project"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
  - package_manager: "javascript"
    directory: "/new_project/examples/btc_eth"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
  - package_manager: "javascript"
    directory: "/new_project/examples/erc20_btc"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
  - package_manager: "javascript"
    directory: "/new_project/examples/separate_apps"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
