[package]
name = "create-comit-app"
version = "0.7.0"
authors = ["CoBloX developers <team@coblox.tech>"]
edition = "2018"

[dependencies]
flate2 = "1.0.13"
structopt = "0.3"
tar = "0.4"
tokio = "0.2"
tokio-compat = "0.1"

[build-dependencies]
anyhow = "1.0.26"
flate2 = "1.0.13"
ignore = "0.4.10"
tar = "0.4.26"
